# Generated by Django 5.1.5 on 2025-02-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_terrain_latitude_terrain_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrain',
            name='location',
        ),
        migrations.AlterField(
            model_name='terrain',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
    ]
