# Generated by Django 5.1.5 on 2025-03-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_terrain_location_alter_terrain_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='climate_zone',
            field=models.CharField(choices=[('tropical wet & dry (Aw)', 'Tropical húmedo y seco'), ('tropical wet (Ar)', 'Tropical húmedo'), ('desert or arid (Bw)', 'Desierto o árido'), ('steppe or semiarid (Bs)', 'Estepa o semiárido'), ('subtropical humid (Cf)', 'Subtropical húmedo'), ('subtropical dry summer (Cs)', 'Subtropical con verano seco'), ('subtropical dry winter (Cw)', 'Subtropical con invierno seco'), ('temperate oceanic (Do)', 'Templado oceánico'), ('temperate continental (Dc)', 'Templado continental'), ('temperate with humid winters (Df)', 'Templado con inviernos húmedos'), ('temperate with dry winters (Dw)', 'Templado con inviernos secos'), ('boreal (E)', 'Boreal'), ('polar (F)', 'Polar')], default='tropical wet & dry (Aw)', max_length=100),
        ),
    ]
